In [1]:
from nltk.tokenize import word_tokenize
#from nltk.corpus import stopwords
#from nltk.stem import PorterStemmer
import matplotlib.pyplot as plt
#from wordcloud import WordCloud
#from math import log, sqrt
import pandas as pd
import numpy as np
import re
%matplotlib inline

In [2]:
mails = pd.read_csv('spam_data.csv', encoding = 'latin-1')
mails.head()

v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
corpus=[]
labs=mails['v1']
data=mails['v2']
for i in range(len(mails)):
    corpus.append((str(data[i])))


In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(corpus).toarray()
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [43]:
from sklearn import preprocessing
labs=mails['v1']
le = preprocessing.LabelEncoder()
Y = le.fit_transform(labs)

In [44]:
Y=Y.reshape(-1,1)

# Machine learning

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import make_scorer, accuracy_score, precision_score, recall_score, f1_score
print("-----------------------------------------DT---------------------------------")

model = DecisionTreeClassifier()
ypredict2=cross_val_predict(model2,X,Y,cv=3)
accuracy2=accuracy_score(Y,ypredict2)
recall2 = recall_score(Y,ypredict2,average='macro')
precision2 = precision_score(Y,ypredict2,average='macro')
f2 = f1_score(Y,ypredict2,average='macro')
print(accuracy2,precision2 ,recall2 ,f2)

In [ ]:
from sklearn.metrics import confusion_matrix

confusion_matrix(Y, ypredict2)

# Deeplearning

In [48]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(handle_unknown='ignore')
x1 = [[0],[1]]
enc.fit(x1)
Y1 = enc.transform(Y).toarray()

In [49]:
Y1

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [55]:
from sklearn.model_selection import train_test_split
x_train,x_valid,y_train,y_valid=train_test_split(X,Y1,test_size=0.2)
y_train.shape

(4457, 2)

In [56]:
x_train1= np.reshape(x_train,x_train.shape+(1,))
np.shape(x_train1)
x_valid1= np.reshape(x_valid,x_valid.shape+(1,))
np.shape(x_valid1)
#x_valid1= np.reshape(x_valid,(np.shape(x_valid.shape),1))
#np.shape(x_valid1)

(1115, 8404, 1)

In [57]:
print(np.shape(x_train1))
print(np.shape(y_train))

(4457, 8404, 1)
(4457, 2)


In [53]:
from keras.models import Sequential
from keras.layers import Dense, Embedding, LSTM
batch_size = 50

model = Sequential()
#model.add(LSTM(128, activation='relu', input_shape=x_train1.shape[1:],return_sequences=True))
model.add(LSTM(16, activation='relu', input_shape=x_train1.shape[1:]))
#model.add(LSTM(128, activation='tanh',return_sequences=True))
#model.add(LSTM(128, activation='tanh'))
model.add(Dense(2, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

#model.add(Dense(1, activation='softmax'))
#model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy', 'binary_accuracy'])
model.summary()

Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 16)                1152      
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 34        
Total params: 1,186
Trainable params: 1,186
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x_train1, y_train,
          batch_size=batch_size, epochs=1,
          shuffle=True, validation_data=(x_valid1, y_valid),verbose=1)

Instructions for updating:
Use tf.cast instead.
Train on 4457 samples, validate on 1115 samples
Epoch 1/1
2800/4457 [=================>............] - ETA: 5:35 - loss: nan - acc: 0.8604